/**
 * Comprehensive list of countries with their demonyms (nationality names)
 * Used for nationality selection in visa and booking forms
 */

export interface Country {
    code: string;      // ISO 3166-1 alpha-2 code
    name: string;      // Country name
    demonym: string;   // Nationality demonym (e.g., "Indian", "American")
}

export const COUNTRIES: Country[] = [
    { code: "AF", name: "Afghanistan", demonym: "Afghan" },
    { code: "AL", name: "Albania", demonym: "Albanian" },
    { code: "DZ", name: "Algeria", demonym: "Algerian" },
    { code: "AD", name: "Andorra", demonym: "Andorran" },
    { code: "AO", name: "Angola", demonym: "Angolan" },
    { code: "AG", name: "Antigua and Barbuda", demonym: "Antiguan" },
    { code: "AR", name: "Argentina", demonym: "Argentine" },
    { code: "AM", name: "Armenia", demonym: "Armenian" },
    { code: "AU", name: "Australia", demonym: "Australian" },
    { code: "AT", name: "Austria", demonym: "Austrian" },
    { code: "AZ", name: "Azerbaijan", demonym: "Azerbaijani" },
    { code: "BS", name: "Bahamas", demonym: "Bahamian" },
    { code: "BH", name: "Bahrain", demonym: "Bahraini" },
    { code: "BD", name: "Bangladesh", demonym: "Bangladeshi" },
    { code: "BB", name: "Barbados", demonym: "Barbadian" },
    { code: "BY", name: "Belarus", demonym: "Belarusian" },
    { code: "BE", name: "Belgium", demonym: "Belgian" },
    { code: "BZ", name: "Belize", demonym: "Belizean" },
    { code: "BJ", name: "Benin", demonym: "Beninese" },
    { code: "BT", name: "Bhutan", demonym: "Bhutanese" },
    { code: "BO", name: "Bolivia", demonym: "Bolivian" },
    { code: "BA", name: "Bosnia and Herzegovina", demonym: "Bosnian" },
    { code: "BW", name: "Botswana", demonym: "Motswana" },
    { code: "BR", name: "Brazil", demonym: "Brazilian" },
    { code: "BN", name: "Brunei", demonym: "Bruneian" },
    { code: "BG", name: "Bulgaria", demonym: "Bulgarian" },
    { code: "BF", name: "Burkina Faso", demonym: "Burkinabe" },
    { code: "BI", name: "Burundi", demonym: "Burundian" },
    { code: "CV", name: "Cabo Verde", demonym: "Cape Verdean" },
    { code: "KH", name: "Cambodia", demonym: "Cambodian" },
    { code: "CM", name: "Cameroon", demonym: "Cameroonian" },
    { code: "CA", name: "Canada", demonym: "Canadian" },
    { code: "CF", name: "Central African Republic", demonym: "Central African" },
    { code: "TD", name: "Chad", demonym: "Chadian" },
    { code: "CL", name: "Chile", demonym: "Chilean" },
    { code: "CN", name: "China", demonym: "Chinese" },
    { code: "CO", name: "Colombia", demonym: "Colombian" },
    { code: "KM", name: "Comoros", demonym: "Comorian" },
    { code: "CG", name: "Congo", demonym: "Congolese" },
    { code: "CD", name: "Congo (Democratic Republic)", demonym: "Congolese" },
    { code: "CR", name: "Costa Rica", demonym: "Costa Rican" },
    { code: "CI", name: "Côte d'Ivoire", demonym: "Ivorian" },
    { code: "HR", name: "Croatia", demonym: "Croatian" },
    { code: "CU", name: "Cuba", demonym: "Cuban" },
    { code: "CY", name: "Cyprus", demonym: "Cypriot" },
    { code: "CZ", name: "Czechia", demonym: "Czech" },
    { code: "DK", name: "Denmark", demonym: "Danish" },
    { code: "DJ", name: "Djibouti", demonym: "Djiboutian" },
    { code: "DM", name: "Dominica", demonym: "Dominican" },
    { code: "DO", name: "Dominican Republic", demonym: "Dominican" },
    { code: "EC", name: "Ecuador", demonym: "Ecuadorian" },
    { code: "EG", name: "Egypt", demonym: "Egyptian" },
    { code: "SV", name: "El Salvador", demonym: "Salvadoran" },
    { code: "GQ", name: "Equatorial Guinea", demonym: "Equatoguinean" },
    { code: "ER", name: "Eritrea", demonym: "Eritrean" },
    { code: "EE", name: "Estonia", demonym: "Estonian" },
    { code: "SZ", name: "Eswatini", demonym: "Swazi" },
    { code: "ET", name: "Ethiopia", demonym: "Ethiopian" },
    { code: "FJ", name: "Fiji", demonym: "Fijian" },
    { code: "FI", name: "Finland", demonym: "Finnish" },
    { code: "FR", name: "France", demonym: "French" },
    { code: "GA", name: "Gabon", demonym: "Gabonese" },
    { code: "GM", name: "Gambia", demonym: "Gambian" },
    { code: "GE", name: "Georgia", demonym: "Georgian" },
    { code: "DE", name: "Germany", demonym: "German" },
    { code: "GH", name: "Ghana", demonym: "Ghanaian" },
    { code: "GR", name: "Greece", demonym: "Greek" },
    { code: "GD", name: "Grenada", demonym: "Grenadian" },
    { code: "GT", name: "Guatemala", demonym: "Guatemalan" },
    { code: "GN", name: "Guinea", demonym: "Guinean" },
    { code: "GW", name: "Guinea-Bissau", demonym: "Bissau-Guinean" },
    { code: "GY", name: "Guyana", demonym: "Guyanese" },
    { code: "HT", name: "Haiti", demonym: "Haitian" },
    { code: "HN", name: "Honduras", demonym: "Honduran" },
    { code: "HU", name: "Hungary", demonym: "Hungarian" },
    { code: "IS", name: "Iceland", demonym: "Icelandic" },
    { code: "IN", name: "India", demonym: "Indian" },
    { code: "ID", name: "Indonesia", demonym: "Indonesian" },
    { code: "IR", name: "Iran", demonym: "Iranian" },
    { code: "IQ", name: "Iraq", demonym: "Iraqi" },
    { code: "IE", name: "Ireland", demonym: "Irish" },
    { code: "IL", name: "Israel", demonym: "Israeli" },
    { code: "IT", name: "Italy", demonym: "Italian" },
    { code: "JM", name: "Jamaica", demonym: "Jamaican" },
    { code: "JP", name: "Japan", demonym: "Japanese" },
    { code: "JO", name: "Jordan", demonym: "Jordanian" },
    { code: "KZ", name: "Kazakhstan", demonym: "Kazakhstani" },
    { code: "KE", name: "Kenya", demonym: "Kenyan" },
    { code: "KI", name: "Kiribati", demonym: "I-Kiribati" },
    { code: "KP", name: "Korea (North)", demonym: "North Korean" },
    { code: "KR", name: "Korea (South)", demonym: "South Korean" },
    { code: "KW", name: "Kuwait", demonym: "Kuwaiti" },
    { code: "KG", name: "Kyrgyzstan", demonym: "Kyrgyzstani" },
    { code: "LA", name: "Laos", demonym: "Laotian" },
    { code: "LV", name: "Latvia", demonym: "Latvian" },
    { code: "LB", name: "Lebanon", demonym: "Lebanese" },
    { code: "LS", name: "Lesotho", demonym: "Mosotho" },
    { code: "LR", name: "Liberia", demonym: "Liberian" },
    { code: "LY", name: "Libya", demonym: "Libyan" },
    { code: "LI", name: "Liechtenstein", demonym: "Liechtensteiner" },
    { code: "LT", name: "Lithuania", demonym: "Lithuanian" },
    { code: "LU", name: "Luxembourg", demonym: "Luxembourger" },
    { code: "MG", name: "Madagascar", demonym: "Malagasy" },
    { code: "MW", name: "Malawi", demonym: "Malawian" },
    { code: "MY", name: "Malaysia", demonym: "Malaysian" },
    { code: "MV", name: "Maldives", demonym: "Maldivian" },
    { code: "ML", name: "Mali", demonym: "Malian" },
    { code: "MT", name: "Malta", demonym: "Maltese" },
    { code: "MH", name: "Marshall Islands", demonym: "Marshallese" },
    { code: "MR", name: "Mauritania", demonym: "Mauritanian" },
    { code: "MU", name: "Mauritius", demonym: "Mauritian" },
    { code: "MX", name: "Mexico", demonym: "Mexican" },
    { code: "FM", name: "Micronesia", demonym: "Micronesian" },
    { code: "MD", name: "Moldova", demonym: "Moldovan" },
    { code: "MC", name: "Monaco", demonym: "Monegasque" },
    { code: "MN", name: "Mongolia", demonym: "Mongolian" },
    { code: "ME", name: "Montenegro", demonym: "Montenegrin" },
    { code: "MA", name: "Morocco", demonym: "Moroccan" },
    { code: "MZ", name: "Mozambique", demonym: "Mozambican" },
    { code: "MM", name: "Myanmar", demonym: "Burmese" },
    { code: "NA", name: "Namibia", demonym: "Namibian" },
    { code: "NR", name: "Nauru", demonym: "Nauruan" },
    { code: "NP", name: "Nepal", demonym: "Nepali" },
    { code: "NL", name: "Netherlands", demonym: "Dutch" },
    { code: "NZ", name: "New Zealand", demonym: "New Zealander" },
    { code: "NI", name: "Nicaragua", demonym: "Nicaraguan" },
    { code: "NE", name: "Niger", demonym: "Nigerien" },
    { code: "NG", name: "Nigeria", demonym: "Nigerian" },
    { code: "MK", name: "North Macedonia", demonym: "Macedonian" },
    { code: "NO", name: "Norway", demonym: "Norwegian" },
    { code: "OM", name: "Oman", demonym: "Omani" },
    { code: "PK", name: "Pakistan", demonym: "Pakistani" },
    { code: "PW", name: "Palau", demonym: "Palauan" },
    { code: "PS", name: "Palestine", demonym: "Palestinian" },
    { code: "PA", name: "Panama", demonym: "Panamanian" },
    { code: "PG", name: "Papua New Guinea", demonym: "Papua New Guinean" },
    { code: "PY", name: "Paraguay", demonym: "Paraguayan" },
    { code: "PE", name: "Peru", demonym: "Peruvian" },
    { code: "PH", name: "Philippines", demonym: "Filipino" },
    { code: "PL", name: "Poland", demonym: "Polish" },
    { code: "PT", name: "Portugal", demonym: "Portuguese" },
    { code: "QA", name: "Qatar", demonym: "Qatari" },
    { code: "RO", name: "Romania", demonym: "Romanian" },
    { code: "RU", name: "Russia", demonym: "Russian" },
    { code: "RW", name: "Rwanda", demonym: "Rwandan" },
    { code: "KN", name: "Saint Kitts and Nevis", demonym: "Kittitian" },
    { code: "LC", name: "Saint Lucia", demonym: "Saint Lucian" },
    { code: "VC", name: "Saint Vincent and the Grenadines", demonym: "Vincentian" },
    { code: "WS", name: "Samoa", demonym: "Samoan" },
    { code: "SM", name: "San Marino", demonym: "Sammarinese" },
    { code: "ST", name: "Sao Tome and Principe", demonym: "Sao Tomean" },
    { code: "SA", name: "Saudi Arabia", demonym: "Saudi" },
    { code: "SN", name: "Senegal", demonym: "Senegalese" },
    { code: "RS", name: "Serbia", demonym: "Serbian" },
    { code: "SC", name: "Seychelles", demonym: "Seychellois" },
    { code: "SL", name: "Sierra Leone", demonym: "Sierra Leonean" },
    { code: "SG", name: "Singapore", demonym: "Singaporean" },
    { code: "SK", name: "Slovakia", demonym: "Slovak" },
    { code: "SI", name: "Slovenia", demonym: "Slovenian" },
    { code: "SB", name: "Solomon Islands", demonym: "Solomon Islander" },
    { code: "SO", name: "Somalia", demonym: "Somali" },
    { code: "ZA", name: "South Africa", demonym: "South African" },
    { code: "SS", name: "South Sudan", demonym: "South Sudanese" },
    { code: "ES", name: "Spain", demonym: "Spanish" },
    { code: "LK", name: "Sri Lanka", demonym: "Sri Lankan" },
    { code: "SD", name: "Sudan", demonym: "Sudanese" },
    { code: "SR", name: "Suriname", demonym: "Surinamese" },
    { code: "SE", name: "Sweden", demonym: "Swedish" },
    { code: "CH", name: "Switzerland", demonym: "Swiss" },
    { code: "SY", name: "Syria", demonym: "Syrian" },
    { code: "TW", name: "Taiwan", demonym: "Taiwanese" },
    { code: "TJ", name: "Tajikistan", demonym: "Tajikistani" },
    { code: "TZ", name: "Tanzania", demonym: "Tanzanian" },
    { code: "TH", name: "Thailand", demonym: "Thai" },
    { code: "TL", name: "Timor-Leste", demonym: "Timorese" },
    { code: "TG", name: "Togo", demonym: "Togolese" },
    { code: "TO", name: "Tonga", demonym: "Tongan" },
    { code: "TT", name: "Trinidad and Tobago", demonym: "Trinidadian" },
    { code: "TN", name: "Tunisia", demonym: "Tunisian" },
    { code: "TR", name: "Turkey", demonym: "Turkish" },
    { code: "TM", name: "Turkmenistan", demonym: "Turkmen" },
    { code: "TV", name: "Tuvalu", demonym: "Tuvaluan" },
    { code: "UG", name: "Uganda", demonym: "Ugandan" },
    { code: "UA", name: "Ukraine", demonym: "Ukrainian" },
    { code: "AE", name: "United Arab Emirates", demonym: "Emirati" },
    { code: "GB", name: "United Kingdom", demonym: "British" },
    { code: "US", name: "United States", demonym: "American" },
    { code: "UY", name: "Uruguay", demonym: "Uruguayan" },
    { code: "UZ", name: "Uzbekistan", demonym: "Uzbekistani" },
    { code: "VU", name: "Vanuatu", demonym: "Ni-Vanuatu" },
    { code: "VA", name: "Vatican City", demonym: "Vatican" },
    { code: "VE", name: "Venezuela", demonym: "Venezuelan" },
    { code: "VN", name: "Vietnam", demonym: "Vietnamese" },
    { code: "YE", name: "Yemen", demonym: "Yemeni" },
    { code: "ZM", name: "Zambia", demonym: "Zambian" },
    { code: "ZW", name: "Zimbabwe", demonym: "Zimbabwean" },
];

// Pre-sorted by demonym for dropdown display
export const COUNTRIES_BY_DEMONYM = [...COUNTRIES].sort((a, b) =>
    a.demonym.localeCompare(b.demonym)
);

// Helper to find country by demonym
export function findCountryByDemonym(demonym: string): Country | undefined {
    const normalized = demonym.trim().toLowerCase();
    return COUNTRIES.find(c => c.demonym.toLowerCase() === normalized);
}

// Helper to search countries by demonym or name
export function searchCountries(query: string): Country[] {
    const normalized = query.trim().toLowerCase();
    if (!normalized) return COUNTRIES_BY_DEMONYM;

    return COUNTRIES_BY_DEMONYM.filter(c =>
        c.demonym.toLowerCase().includes(normalized) ||
        c.name.toLowerCase().includes(normalized)
    );
}
