/**
 * SMS Utility
 * Handles OTP verification using SMS API
 */

const MSG91_AUTH_KEY = process.env.MSG91_AUTH_KEY;

/**
 * Verifies the OTP token against SMS API
 * @param mobile - The mobile number with country code (e.g., 919999999999)
 * @param otpToken - The token/OTP to verify (Widget returns a token, or standard OTP)
 * @returns Promise<{ success: boolean; message: string }>
 */
export async function verifySMSOTP(mobile: string, otpToken: string) {
    if (!MSG91_AUTH_KEY) {
        console.error("MSG91_AUTH_KEY is not defined in environment variables");
        return { success: false, message: "Configuration error" };
    }

    try {
        // Remove '+' if present from mobile
        const cleanMobile = mobile.replace("+", "");

        // MSG91 OTP Verification API
        // https://docs.msg91.com/p/tf9vsw6un/v/6v3r7z/otp/verify-otp
        const response = await fetch(
            `https://control.msg91.com/api/v5/otp/verify?otp=${otpToken}&mobile=${cleanMobile}&authkey=${MSG91_AUTH_KEY}`,
            {
                method: "GET",
            }
        );

        const data = await response.json();

        if (data.type === "success") {
            return { success: true, message: data.message };
        } else {
            console.warn("[SMS] OTP Verification Failed:", data);
            return { success: false, message: data.message || "Invalid OTP" };
        }
    } catch (error) {
        console.error("[SMS] Error verifying OTP:", error);
        return { success: false, message: "Verification failed" };
    }
}

/**
 * Resends the OTP using SMS retry API
 * @param mobile - The mobile number with country code
 * @returns Promise<{ success: boolean; message: string }>
 */
export async function resendSMSOTP(mobile: string) {
    if (!MSG91_AUTH_KEY) {
        return { success: false, message: "Configuration error" };
    }

    try {
        const cleanMobile = mobile.replace("+", "");
        const response = await fetch(
            `https://control.msg91.com/api/v5/otp/retry?authkey=${MSG91_AUTH_KEY.trim()}&mobile=${cleanMobile}&retrytype=text`,
            { method: "GET" }
        );
        const data = await response.json();
        return { success: data.type === "success", message: data.message };
    } catch (error) {
        console.error("[SMS] Error resending OTP:", error);
        return { success: false, message: "Resend failed" };
    }
}

/**
 * Manual verification of Widget OTP using requestId
 * @param requestId - The requestId from sendOtp response
 * @param otp - The 4-6 digit OTP
 * @returns Promise<{ success: boolean; message: string }>
 */
export async function verifySMSWidgetOTP(requestId: string, otp: string) {
    if (!MSG91_AUTH_KEY) {
        return { success: false, message: "Configuration error" };
    }

    try {
        const response = await fetch(
            `https://api.msg91.com/api/v5/widget/verifyOtp`,
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "authkey": MSG91_AUTH_KEY.trim(),
                },
                body: JSON.stringify({
                    widgetId: process.env.NEXT_PUBLIC_MSG91_WIDGET_ID,
                    reqId: requestId,
                    otp: otp
                })
            }
        );
        const data = await response.json();
        return { success: data.type === "success", message: data.message };
    } catch (error) {
        console.error("[SMS] Error in widget manual verify:", error);
        return { success: false, message: "Verification failed" };
    }
}
/**
 * Verifies the Access Token generated by SMS Widget
 * @param accessToken - The JWT token generated by the widget after successful OTP verification
 * @returns Promise<{ success: boolean; message: string; mobile?: string }>
 */
export async function verifySMSAccessToken(accessToken: string) {
    if (!MSG91_AUTH_KEY) {
        console.error("[SMS] ERROR: Auth key is missing from environment");
        return { success: false, message: "Server configuration error" };
    }

    const authKey = MSG91_AUTH_KEY.trim();

    try {
        console.log("[SMS] Server-side verification for token:", accessToken.substring(0, 20) + "...");

        // Try api.msg91.com with authkey in both URL and headers to be absolutely certain
        const url = `https://api.msg91.com/api/v5/widget/verifyAccessToken?authkey=${authKey}`;

        let response = await fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "authkey": authKey,
            },
            body: JSON.stringify({
                "access-token": accessToken
            })
        });

        let data = await response.json();
        console.log("[SMS] Response (Primary):", JSON.stringify(data));

        // Fallback to control.msg91.com if the first one fails
        if (data.type !== "success") {
            console.log("[SMS] Retrying via fallback...");
            const fallbackUrl = `https://control.msg91.com/api/v5/widget/verifyAccessToken?authkey=${authKey}`;
            const fallbackResponse = await fetch(fallbackUrl, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "authkey": authKey,
                },
                body: JSON.stringify({
                    "access-token": accessToken
                })
            });
            const fallbackData = await fallbackResponse.json();
            console.log("[SMS] Response (Fallback):", JSON.stringify(fallbackData));

            if (fallbackData.type === "success") {
                data = fallbackData;
            }
        }

        if (data.type === "success") {
            const mobile = data.mobile_number || data.mobile || (data.data && (data.data.mobile_number || data.data.mobile));
            console.log("[SMS] Verification SUCCESS for mobile:", mobile);
            return {
                success: true,
                message: data.message,
                mobile: mobile
            };
        } else {
            console.warn("[SMS] Verification FAILED:", data.message || data);
            return {
                success: false,
                message: data.message || "Invalid or expired session"
            };
        }
    } catch (error) {
        console.error("[SMS] Exception during server verification:", error);
        return { success: false, message: "Internal verification error" };
    }
}
